--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/igniscyan/.config/wpg/wallpapers/wallhaven-735042.jpg"

-- Special
background="#181c22"
foreground="#fdffff"
cursor="#fdffff"

-- Colors
color0="#181c22"
color1="#ab494b"
color2="#a398a8"
color3="#ac5f6a"
color4="#5579ac"
color5="#ab7a88"
color6="#7a91ab"
color7="#c5c6c7"
color8="#2c343f"
color9="#ee4f52"
color10="#dbb0ef"
color11="#f06a7d"
color12="#5d9af0"
color13="#f18ba8"
color14="#8bbbf1"
color15="#fdffff"
